"""
Django settings for lastbite project.
Generated by 'django-admin startproject' using Django 5.2
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ===========================================================
# SECURITY
# ===========================================================
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-f4b0()y0xii)mw_3f-!i0p4v(m=ptv1u7wq14%(lsj%1a#a!08')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost 127.0.0.1').split()

# ===========================================================
# APPLICATIONS
# ===========================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # LastBite apps
    'main',
    'surprise_bag',
    'order',
    # 'merchant_store',  # TODO: uncomment setelah branch merchant_store di-merge
    'community',
    'eco_impact',
]

# ===========================================================
# MIDDLEWARE
# ===========================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lastbite.urls'

# ===========================================================
# TEMPLATES
# ===========================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lastbite.wsgi.application'

# ===========================================================
# DATABASE
# ===========================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'fathir.atha',
        'USER': 'fathir.atha',
        'PASSWORD': 'Q00U2X1ruoFjnw4Nz7C6lxRuRuOvocRY',
        'HOST': 'pws.cs.ui.ac.id',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=lastbite,public'
        },
    }
}

# ===========================================================
# PASSWORD VALIDATION
# ===========================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===========================================================
# INTERNATIONALIZATION
# ===========================================================
LANGUAGE_CODE = 'id'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True

# ===========================================================
# STATIC FILES
# ===========================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files (development)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ===========================================================
# DEFAULT PRIMARY KEY
# ===========================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===========================================================
# CSRF TRUSTED ORIGINS (for PWS deployment)
# ===========================================================
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost http://127.0.0.1'
).split()

# ===========================================================
# SECURITY SETTINGS (production only)
# ===========================================================
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
